# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.main_tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.main_tabWidget.setObjectName("main_tabWidget")

        # Tab 1: CRUD Employee
        self.tab_crud_employee = QtWidgets.QWidget()
        self.tab_crud_employee.setObjectName("tab_crud_employee")
        self.crud_layout = QtWidgets.QVBoxLayout(self.tab_crud_employee)
        self.crud_layout.addWidget(QtWidgets.QLabel("QUẢN LÝ EMPLOYEE (ADMIN)", parent=self.tab_crud_employee))
        # Nơi đây sẽ thêm QTableWidget, QLineEdit và các button (Add, Update, Delete)
        self.main_tabWidget.addTab(self.tab_crud_employee, "")

        # Tab 2: Thống kê
        self.tab_statistics = QtWidgets.QWidget()
        self.tab_statistics.setObjectName("tab_statistics")
        self.stats_layout = QtWidgets.QVBoxLayout(self.tab_statistics)
        self.stats_layout.addWidget(QtWidgets.QLabel("THỐNG KÊ (ADMIN, REPORTER)", parent=self.tab_statistics))
        # Nơi đây sẽ thêm các button, QDateEdit (T1, T2), QSpinBox (Top N) và khu vực hiển thị (QTextEdit, QTableWidget, Matplotlib Canvas)
        self.main_tabWidget.addTab(self.tab_statistics, "")

        # Tab 3: Machine Learning
        self.tab_ml = QtWidgets.QWidget()
        self.tab_ml.setObjectName("tab_ml")
        self.ml_layout = QtWidgets.QVBoxLayout(self.tab_ml)
        self.ml_layout.addWidget(QtWidgets.QLabel("MACHINE LEARNING (ADMIN, TECHNICAL)", parent=self.tab_ml))
        # Nơi đây sẽ thêm các button (Train, Predict) và các QLineEdit cho input features
        self.main_tabWidget.addTab(self.tab_ml, "")

        self.gridLayout.addWidget(self.main_tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.main_tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Hệ thống Quản lý và Dự báo"))
        self.main_tabWidget.setTabText(self.main_tabWidget.indexOf(self.tab_crud_employee),
                                       _translate("MainWindow", "Quản lý Employee"))
        self.main_tabWidget.setTabText(self.main_tabWidget.indexOf(self.tab_statistics),
                                       _translate("MainWindow", "Thống kê Báo cáo"))
        self.main_tabWidget.setTabText(self.main_tabWidget.indexOf(self.tab_ml),
                                       _translate("MainWindow", "Machine Learning"))